### PR TITLE
Bundle of fixes/updates for WorldPay JSON Gateway

### PR DESCRIPTION
**Pull request by leith**
This PR comes from writing an integration after @lukeholder's #22 was merged. I'm not entirely sure how @ugin is able to use this commercially because at the moment, the library will _treat declined cards as successful payments_.

This is what I've done:
* Fix incorrect response class being generated (causes card declines to be accepted)
* Fix purchase response message to actually have failure reason if available (instead of an error from no 'message')
* Add more docblocks
* Add proper abstract function definition for getEndpoint
* Abstract JsonAuthorizeResponse to reduce duplication
* Update unit test coverage, including distinction between failure, error and malformed cases

It's also worth noting that the `JsonCaptureRequest` class still has _no_ unit tests - I'm not using it in my current integration yet, so I'm unlikely to add more coverage for this any time soon. Hopefully someone using it will be able to look into that in more detail.

### CODE REVIEW

**Comment by lukeholder** [comment]
Thanks @leith -  looks good.

**Comment by kynx** [comment]
@delatbabel Any news on this one? I'm looking at integrating WorldPay but the issue @leith uncovered is alarming.

**Comment by lukeholder** [comment]
@delatbabel maybe this can be merged?

**Comment by kynx** [comment]
@delatbabel @lukeholder If it's any help, I've confirmed the problem @leith describes exists against a WorldPay account and that this PR fixes the problem. Would be great to get this merged.

**Comment by barryvdh** [comment]
Merged and tagged v2.2.1

**Pull request merged**
