### PR TITLE
Compatibility with omnipay-common:^3.0

### PR DESCRIPTION
**Pull request by dpfaffenbauer**
This PR makes WorldPay compatible with the latest Omnipay Alpha and merges also PR #26 (makes total sense to me, so I merged it here as well, if you wanna see only changes for the newest version, have a look at https://github.com/thephpleague/omnipay-worldpay/commit/87a2d03c32b713b4bacf6cb32093565f5f00f34c)

This is necessary to make omnipay-worldpay compatible with symfony-stack 3.*.

### CODE REVIEW

**Comment by KirbyFox** [comment]
Thanks very much @dpfaffenbauer Are these improvements likely to fix the issues that I've been experiencing? e.g. https://github.com/thephpleague/omnipay-worldpay/issues/28

**Comment by dpfaffenbauer** [comment]
@KirbyFox don't think so, haven't change any business logic, just compatibility with latest omnipay

**Comment by KirbyFox** [comment]
Thanks @dpfaffenbauer How do I get it to use JsonGateway.php instead of Gateway.php ? Is there a setting that needs to be changed somewhere?

**Comment by dpfaffenbauer** [comment]
@KirbyFox Not sure how to do that with Sylius, but since I am doing it similar as they do it: I am having these two fields inside my Payment Configuration Form:

```php
->add('factory', TextType::class, [
                'data' => 'omnipay',
                'empty_data' => 'omnipay'
            ])
            ->add('type', TextType::class, [
                'data' => 'WorldPay\\Json',
                'empty_data' => 'WorldPay\\Json'
            ])
 ```

This basically sets the config factory to omnipay with type WorldPay\\Json. The rest is done by OmnipayBridge.

**Comment by dpfaffenbauer** [comment]
@amacneil any thoughts on this?

**Comment by StudioMaX** [comment]
ping @barryvdh

**Comment by dpfaffenbauer** [comment]
yeah :) :beers:

**Pull request merged**
