### PR TITLE
Added optional confirm method

### LINKED ISSUE #7: Possiblity of sending meta-refresh page back to WorldPay to redirect customer following purchase
As far as I can tell, there isn't currently the facility in this driver to either display a message/page to the customer following a purchase (other than WorldPay's own page).

One additional downside that I've run into with this is that there doesn't seem to be a way to reset the customer's session/cart following a successful transaction.

In our previous integration (and following how others seem to have tackled this), on receiving the callback from WorldPay, we returned a simple HTML page with a meta-refresh tag in. This gets displayed to the customer, who then in response, gets redirected back to the originating site. 

If I was to provide a pull request with this added functionality, does anyone foresee any issues with this?

### PR DESCRIPTION
**Pull request by coatesap**
This allows us to return the customer to our own domain, following a transaction. Resolves #7.

### CODE REVIEW

**Comment by coatesap** [comment]
Any chance this could be merged? We're waiting to use this in production, but don't want to use a separate fork unless necessary...

**Comment by coatesap** [comment]
@kayladnls Hi Kayla, could you make a new release version so that we can use this via composer?

**Comment by benrolfe** [comment]
@coatesap Does this work locally in **test** mode, or does this only work in **production** mode?

**Comment by coatesap** [comment]
Trying to remember from nearly 2 years ago now, but I'm pretty sure it worked for both test and live payments.

**Pull request merged**
