### PR TITLE
Support for new Worldpay JSON API 

### PR DESCRIPTION
**Pull request by lukeholder**
Only supports the worldpay.js token payments with worldpay.js

Expect a valid `token` param passed to purchase/authorize request.

### CODE REVIEW

**Comment by lukeholder** [comment]
Tests pass. Failure is hhvm on travis CI.

**Comment by lukeholder** [comment]
Fixed #3 and #13

**Comment by coatesap** [comment]
Hi @lukeholder - this looks interesting. Does this method of integration allow you to keep the customer on-site in a similar fashion to Stripe, Braintree, etc?

**Comment by lukeholder** [comment]
@coatesap yes. You generate a token with JavaScript using the worldpay.js script - this works just like stripe. Then you pass the token to your server to send the purchase payment request. Have you tested?

**Comment by ugin** [comment]
This should be merged, I'm using it in Craft Commerce since it was released, no issues so far.

**Comment by delatbabel** [comment]
OK merged, if someone can confirm that it works in production and then I'll tag for release.

**Comment by ugin** [comment]
I use it in production and works properly, due to NDA I cannot share the store link.

**Comment by delatbabel** [comment]
Released as v2.2.1

**Comment by lukeholder** [comment]
Thanks @delatbabel

**Pull request merged**
